### ISSUE TITLE
ntpclient - timeout issue (init.d script)

### ISSUE THREAD

**Issue by ghost** [WAGO/pfc-firmware-sdk-G2#10]
When performing the command:

`/etc/init.d/ntpclient gettimeonce` 

same as in WBM pressing the button (WBN/Ports and Services/NTP Client):
 ![grafik](https://github.com/WAGO/pfc-firmware-sdk-G2/assets/95914791/2a28b749-ca47-4b4e-a88d-673fed06e374)

the following Error keeps appearing and no time update was done.

`No functioning time server found`

Solution on our side:

increasing the timeout limit from 0,5s to 1s in the file `/etc/init.d/ntpclient`

line 67

before:
```sh
    while [ $timeoutticks -lt $maxticks ]; do
        usleep 500000
        if [ ! -d /proc/$ntppid ]; then
            break;
        fi
```
after:
```sh
    while [ $timeoutticks -lt $maxticks ]; do
        usleep 1000000
        if [ ! -d /proc/$ntppid ]; then
            break;
        fi
```

After performing the change inside the init.d script the time gets updated successfully.
![grafik](https://github.com/WAGO/pfc-firmware-sdk-G2/assets/95914791/844b14db-eae4-49b2-b377-ca1795a1ae44)

The following config is used:
- PFC200 750-8212/025-002
- stable LTE Connection via Router

![grafik](https://github.com/WAGO/pfc-firmware-sdk-G2/assets/95914791/12c9a414-0f83-4510-8f37-8299e1f90f5b)

**Comment by falk-werner** [comment]
Hello @oxygen50,

thanks for the issue. It seems that our timeout is too low for your use case. Instead of changing the interval to check whether the ntp client is finished, we prefer to increase the number of retries by setting `maxticks` to 16 instead of 8. By doing so we are more responsive when ntp client finishes quickly.

Will this be sufficient for your use case?

**Comment by ghost** [comment]
Hello @falk-werner,

thanks for the quick reply. I quickly testet you suggestion, which seems to also work.

Edited ntpclient
![grafik](https://github.com/WAGO/pfc-firmware-sdk-G2/assets/95914791/3d0b9e3e-f357-4ba7-9b48-91bba4d68158)

Result:
![grafik](https://github.com/WAGO/pfc-firmware-sdk-G2/assets/95914791/2e66d21a-bf76-4408-a98f-2d49335266ce)

Feel free to implement 👍

**Comment by falk-werner** [comment]
The change will be implemented in FW26 (04.04.xx) since FW25 (04.03.xx) has already entered the testing stage and will be released soon.

**Comment by ghost** [comment]
As the FW25 has been released today: Has this Issue been fixed in FW25 with WAT-35470?

**Comment by falk-werner** [comment]
Sorry, the issue is not fixed in FW25. The fix will be released in FW26 as described above.
WAT-35470 is completely unrelated (not even the same product). Did you have the correct number?

**Comment by ghost** [comment]
Hello @falk-werner 

from the Release notes of the latest FW25 in section 1.1 System

![grafik](https://github.com/WAGO/pfc-firmware-sdk-G2/assets/95914791/bfc6b665-28c5-475b-8614-330d3f21364f)

**Comment by falk-werner** [comment]
This seems to be an error in the release notes. The number of the issue in the release notes is wrong. The correct number of the issue fixed in FW25 is WAT-35478 (8 instead of 0).

Unfortunately, WAT-35478 does not solve your issue. It solves an error that occurs when NTP servers are configured and one of them is not reachable.
